name: Test Composite Action

on: [push]

jobs:
  local-action: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    
    - name: ls
      uses: ./.github/actions/my-actions