name : Test

# on : [push, pull_request]
on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0

    - name: ls
      run: |
        chmod +x script.sh
        ./script.sh

  other:
    runs-on: ubuntu-latest
    # needs: [hola]
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0

    - name: LS
      run: echo "ls -la" && ls -la

    - name: Setup Node.js environment
      uses: actions/setup-node@v5.0.0
    
    - name: node version
      run: node --version
    